### PR TITLE
Use gh actions

### PR DESCRIPTION
**Pull request by jmortlock**
Firstly great to hear development has started on this project again :tada: 

This PR migrates the build system from Travis to Github actions with a couple of improvements.

>     Run the aws_sqs_client_spec against localstack rather than requiring a live integration test.
>     Test against rails from 5.0 to 6.1
>     Add ruby 3 to the build matrix
>     Re-added rails 6 to the gemspec (we use this gem in rails 6 for a long time now)
>     Use the more specific dependency of aws-sdk-sqs so the entire aws-sdk is not pulled in

For the deployed integration test to pass you would need to configure the github repository secrets and enter the relevant aws credentials.

### CODE REVIEW

**Comment by joeyparis** [comment]
What a coincidence, we just had a call on Thursday (laying out the details of transferring ownership, etc.) and one of the things that came up was whether or not we wanted to move to GitHub actions but were kind of on the fence, so I guess this must be a sign!

I'll review the changes Monday or Tuesday and we're hoping for an alpha release this week!

**Comment by joeyparis** [comment]
And about using localstack for  it's almost like you were on the call with us lol

**Comment by jmortlock** [comment]
Good to here we are aligned, for what its worth I think TravisCI now that builds are throttled makes it a much harder sell to stay on it especially when doing matrix types builds.

As for localstack I think the remote integration tests whilst they may have value I personally would not want to be maintaining / supporting them :) I would be looking at what tests I could write so that I didn't have to actually create EB environments to test against.

Anyway look forward to testing out the Alpha next week!

**Comment by januszm** [comment]
Looks good, just one note: we're making the Rails version constraint open-ended,  from `<6` to any, which may be OK, but it's worth having second look at.
When I last added GH Actions to the project, it has already started for PR one, I wonder why it didn't fire here.

**Comment by jmortlock** [comment]
I have been using this gem in a production rails 6 application for at least a year now so I'm confident enough the main functionality works (We don't use cron)

As for GH actions I think it will only trigger when you are creating the branch directly on this repository, you can see the gh-actions firing on my fork here https://github.com/jmortlock/active-elastic-job/actions, obviously the deployed test is failing.

If you want to see the tests yourself you could refork my repo or just replicate my branch in this repository.

**Comment by joeyparis** [comment]
@jmortlock I actually think it's safe to remove the deployed test from gh-actions. We've decided we're only going to run that test before deployments because of the amount of time it adds to each test. So if you can remove that test just from the gh-actions then this should be good to go!

**Comment by januszm** [comment]
> I have been using this gem in a production rails 6 application for at least a year now so I'm confident enough the main functionality works (We don't use cron)
Thanks @jmortlock , when I mentioned open-ended range constraint I meant future versions of Rails (7+). 
An open-ended range constraint has the advantage that if future versions of Rails prove to be compatible with active-elastic-job, we don't need to change anything and we don't have to make a new release. But if it turns out that something is not working, the problem will not be noticed until someone activates it. Just a food for thought, not a big deal atm.

**Pull request merged**
