### PR TITLE
Add support for FIFO queues

### PR DESCRIPTION
**Pull request by styrmis**
This is a resubmission of #78, with the additional work done by @Chacattack (see https://github.com/active-elastic-job/active-elastic-job/pull/78#issuecomment-460497393) to get the tests to pass.

The original implementation has been reduced in scope (the group and deduplication ids are now only set automatically, not explicitly), some bugs were fixed, and a spec added.

### CODE REVIEW

**Comment by styrmis** [comment]
@joeyparis Think this is ready for review—I'm using the originally submitted implementation as a guide for how this is supposed to work, I haven't had a chance to test with a FIFO queue yet.

Not sure how to resolve the last lint issue, are methods to be limited to 12 lines max?

Great to see the tests working so well using Actions!

**Comment by styrmis** [comment]
@joeyparis I'm now running this branch in our staging environment with a FIFO queue, and with a standard queue in production, both appear to be working well.

**Comment by styrmis** [comment]
Found out the hard way that the scheduled jobs in `cron.yaml` are not supported with FIFO queues [[1]](https://aws.amazon.com/premiumsupport/knowledge-center/elastic-beanstalk-cron-job-worker-tier/). This branch appeared to work well in production except for this caveat.

We make use of the cron functionality so I'm going to need to wait for this to be addressed in the worker tier runtime before we can make full use of this.

**Comment by joeyparis** [comment]
@styrmis that's disappointing. Just to clarify, despite that caveat this pull request is still valid/usable for working with FIFO queues?

**Comment by styrmis** [comment]
@joeyparis Yeah it's pretty disappointing—I'm hoping it's just a matter of time before they resolve it, though we could be waiting a while.

I had this branch running in production both with a standard queue and then with a FIFO queue and experienced no issues—jobs were running as before, though the cron/scheduled jobs were absent, so I think it would still be worth merging this for those who wish to use FIFO queues (but not the `cron.yaml` file).

**Pull request merged**
